# @package _global_
defaults:
  - ad_default.yaml

processor:
  _target_: characterization.processors.feature_processor.FeatureProcessor

characterizer:
  _target_: characterization.domains.ad.features.safeshift_features.SafeShiftFeatures
