# @package _global_
defaults:
  - default.yaml
  - individual_features.yaml

processor:
  _target_: characterization.processors.scores_processor.ScoresProcessor

characterizer:
  _target_: characterization.scorer.individual_scorer.IndividualScorer
  config:
    individual_score_function: simple
    score_clip:
      min: 0.0
      max: 150.0
