# @package _global_
defaults:
  - individual_features.yaml
  - scores.yaml

characterizer:
  _target_: characterization.scorer.individual_scorer.IndividualScorer
  config:
    individual_score_function: simple
    score_wrt_ego_only: ${processor.config.score_wrt_ego_only}
    score_clip:
      min: 0.0
      max: 150.0

    weights:
      speed: 0.1
      speed_diff: 1.0
      acceleration: 1.0
      deceleration: 1.0
      jerk: 1.0
      waiting_period: 1.0
      waiting_intervals: 1.0
      waiting_distances: 1.0

    detections:
      speed: 30 # in m/s, i.e. ~108 km/h ~70 mph
      speed_diff: 8 # in m/s, i.e. ~30 km/h over the speed limit
      acceleration: 10 # in m/s^2
      deceleration: 10 # in m/s^2
      jerk: 10 # in m/s^3
      waiting_period: 8 # in seconds
      waiting_intervals: 8 # in number of intervals
      waiting_distances: 8 # in meters
