# @package _global_
defaults:
  - interaction_features.yaml
  - scores.yaml

characterizer:
  _target_: characterization.scorer.interaction_scorer.InteractionScorer
  config:
    interaction_score_function: simple

    score_clip:
      min: 0.0
      max: 150.0

    weights:
      collision: 2.0
      mttcp: 2.0

    detections:
      mttcp: 4
