# @package _global_
defaults:
  - default.yaml
  - interaction_features.yaml

processor:
  _target_: characterization.processors.scores_processor.ScoresProcessor

characterizer:
  _target_: characterization.scorer.interaction_scorer.InteractionScorer
  config:
    interaction_score_function: simple
    score_clip:
      min: 0.0
      max: 200.0
