# @package _global_
defaults:
  - default.yaml

processor:
  _target_: characterization.processors.scores_processor.ScoresProcessor

characterizer:
  _target_: characterization.scorer.safeshift_scorer.SafeShiftScorer
  config:
    individual_score_function: simple
    interaction_score_function: simple
    score_clip:
      min: 0.0
      max: 350.0
