default_stages:
  - pre-commit
  - manual

default_language_version:
  python: python3.12

repos:
  # Autoformats Python code to Black’s style
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        args: ["--line-length=120"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4  # check for latest version: https://github.com/astral-sh/ruff-pre-commit/releases
    hooks:
      - id: ruff
        args: ["--fix"]

  # Static analysis security checker for Python code
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.8
    hooks:
      - id: bandit
        args: ["-r", "src"]

  # Lints Python code for style, syntax, and error-prone patterns
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: ["--max-line-length=120"]

  # Pyright
  - repo: local
    hooks:
      - id: pyright
        name: pyright type check
        entry: pyright
        language: python
        types: [python]
        pass_filenames: false

  # Scans staged files for hardcoded passwords, tokens, and keys
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      # Prevents accidentally committing huge files. Limit set to 1MB.
      - id: check-added-large-files
        args: ["--maxkb=1024", "--enforce-all"]
      # Detects filename case conflicts on case-insensitive filesystems
      - id: check-case-conflict
      # Check that anything with a shebang has the executable bit set
      - id: check-executables-have-shebangs
      # Ensures all files end with a newline (avoids diff noise)
      - id: end-of-file-fixer
      # Removes trailing whitespace in all files
      - id: trailing-whitespace
      # Forbids submodules
      - id: forbid-submodules
      # Don't allow commits to main
      # - id: no-commit-to-branch
      #   args: ["--branch=main"]
      # Validates YAML file syntax
      - id: check-yaml
      # Validates JSON file syntax
      - id: check-json
      # Validates TOML file syntax
      - id: check-toml
      # Blocks commit if leftover merge conflict markers exist
      - id: check-merge-conflict
      # Detect private key
      - id: detect-private-key
