default_stages:
  - pre-commit
  - manual

default_language_version:
  python: python3.12

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.1
    hooks:
      - id: ruff-check
        args: ["--fix"]
      - id: ruff-format

  # Pyright
  - repo: local
    hooks:
      - id: pyright
        name: pyright type check
        entry: pyright
        language: python
        types: [python]
        pass_filenames: false

  # Scans staged files for hardcoded passwords, tokens, and keys
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      # Prevents accidentally committing huge files. Limit set to 1MB.
      - id: check-added-large-files
        args: ["--maxkb=1024", "--enforce-all"]
      # Detects filename case conflicts on case-insensitive filesystems
      - id: check-case-conflict
      # Check that anything with a shebang has the executable bit set
      - id: check-executables-have-shebangs
      # Ensures all files end with a newline (avoids diff noise)
      - id: end-of-file-fixer
      # Removes trailing whitespace in all files
      - id: trailing-whitespace
      # Forbids submodules
      - id: forbid-submodules
      # Don't allow commits to main
      # - id: no-commit-to-branch
      #   args: ["--branch=main"]
      # Validates YAML file syntax
      - id: check-yaml
      # Validates JSON file syntax
      - id: check-json
      # Validates TOML file syntax
      - id: check-toml
      # Blocks commit if leftover merge conflict markers exist
      - id: check-merge-conflict
      # Detect private key
      - id: detect-private-key
