defaults:
  - _self_
  - paths: waymo
  - dataset: waymo
  - characterizer: individual_features
  - debug: null

seed: 42
save: true
overwrite: false

num_scenarios: null
num_shards: 0
shard_index: 0
step: 1
parallel: true
batch_size: 16
num_workers: 16
shuffle: false

scenario_type: 'gt'
return_criterion: 'critical'
ego_only: false
score_wrt_ego_only: false
aggregated_score_weight: 0.5
