_target_: safeair.scenario_visualizer.scenario_visualizer.ScenarioVisualizer

name: scenario
assets_path: ${processor.assets_path}
graph_data_path: ${processor.graph_data_path}
airport: ${processor.airport}
min_valid_timesteps: 2

espg: ESPG:4326 # Map CRS for visualization. Either of 'ESPG:4326' or 'ESPG:3857'

use_icons: true
add_title: false
update_limits: false
show_raster: false
use_latlon: true
display_agent_ids: true
display_only_critical_actypes: true
viz_csi_prediction: false # Whether to visualize CSI predictions
viz_trajpred: false # Whether to visualize trajectory predictions
agent_zoom:
  AIRCRAFT: 0.010
  VEHICLE: 0.15
  UNKNOWN: 0.010

# Panes to plot. Options are:
# - ALL_AGENTS
# - HIGHLIGHT_RELEVANT_AGENTS
# - CRITICAL_SCENARIO
# - CRITICAL_SCENARIO_IDENTIFICATION_PREDICTION
panes_to_plot:
  - HIGHLIGHT_RELEVANT_AGENTS
