defaults:
  - scenario.yaml

_target_: safeair.scenario_visualizer.scenario_trajpred_visualizer.ScenarioTrajpredVisualizer

name: trajpred_scenario
viz_trajpred: true

distance_to_ego_zoom_in: 2.0
display_agent_ids: false
display_only_critical_actypes: false
pred_colormap: cool_r
