# path to root directory
# this requires PROJECT_ROOT environment variable to exist
# you can replace it with "." if you want the root to be the current working directory
root_dir: ${oc.env:PROJECT_ROOT}
tag: 'default'

# Data paths
base_path: ./data/aviation/${scenario.dataset_name}
assets_path: ${paths.base_path}/assets

graph_data_version: a42v01
graph_data_path: ${paths.base_path}/graph_data_${paths.graph_data_version}

traj_data_version: a42v01
traj_data_path: ${paths.base_path}/traj_data_${paths.traj_data_version}

raw_traj_data_path: ${paths.traj_data_path}/raw_trajectories
proc_traj_data_path: ${paths.traj_data_path}/proc_trajectories
traj_summary_path: ${paths.traj_data_path}/proc_summary
splits_path: ${paths.traj_data_path}/splits

data_cache_path: ${paths.base_path}/data_cache
temp_path: "temp"

# path to output directory, created dynamically by hydra
# path generation pattern is specified in `configs/hydra/default.yaml`
# use it to store all files generated during the run, like ckpts and metrics
# path to working directory
work_dir: ${hydra:runtime.cwd}
output_dir: ${hydra:runtime.output_dir}

# Temporary outputs
experiment_cache_path: ${paths.base_path}/model_cache/${paths.tag}
experiment_dir: ${exp_name}_${now:%Y-%m-%d}_${now:%H-%M-%S}
meta_path: ${paths.experiment_cache_path}/${paths.experiment_dir}/meta
log_path: ${paths.experiment_cache_path}/${paths.experiment_dir}/logs
ckpt_path: ${paths.experiment_cache_path}/${paths.experiment_dir}/ckpts
batch_cache_path: ${paths.experiment_cache_path}/${paths.experiment_dir}/batch_cache
analysis_path: ${paths.experiment_cache_path}/${paths.experiment_dir}/analysis
viz_path: ${paths.experiment_cache_path}/${paths.experiment_dir}/viz

train_data_path: null
val_data_path: null
test_data_path: null

train_split_path: null
val_split_path: null
test_split_path: null

train_data_tag: null
val_data_tag: null
test_data_tag: null
