# Benchmark source: graph-analysis_net-lsd_norm-laplacian_simplified_workers-16_clustering-kmeans_num-clusters-3

defaults:
  - default.yaml

tag: 'environment-cluster2'

base_path: ./data/
graph_data_version: a42v01
traj_data_version: a42v01

train_data_path: [
  # keep-sorted start
  "${paths.proc_traj_data_path}/kcle",
  "${paths.proc_traj_data_path}/khou",
  "${paths.proc_traj_data_path}/kmke",
  "${paths.proc_traj_data_path}/kpdx",
  # keep-sorted end
]
train_split_path: [
  # keep-sorted start
  "${paths.splits_path}/kcle/kcle_day_splits.json",
  "${paths.splits_path}/khou/khou_day_splits.json",
  "${paths.splits_path}/kmke/kmke_day_splits.json",
  "${paths.splits_path}/kpdx/kpdx_day_splits.json",
  # keep-sorted end
]
train_data_tag: [
  # keep-sorted start
  "kcle-training",
  "khou-training",
  "kmke-training",
  "kpdx-training",
  # keep-sorted end
]

val_data_path: [
  # keep-sorted start
  "${paths.proc_traj_data_path}/kcle",
  "${paths.proc_traj_data_path}/khou",
  "${paths.proc_traj_data_path}/kmke",
  "${paths.proc_traj_data_path}/kpdx",
  # keep-sorted end
]
val_split_path: [
  # keep-sorted start
  "${paths.splits_path}/kcle/kcle_day_splits.json",
  "${paths.splits_path}/khou/khou_day_splits.json",
  "${paths.splits_path}/kmke/kmke_day_splits.json",
  "${paths.splits_path}/kpdx/kpdx_day_splits.json",
  # keep-sorted end
]
val_data_tag: [
  # keep-sorted start
  "kcle-validation",
  "khou-validation",
  "kmke-validation",
  "kpdx-validation",
  # keep-sorted end
]

test_data_path: [
  # cluster_0 unseen-easy
  "${paths.proc_traj_data_path}/kdfw",
  "${paths.proc_traj_data_path}/klas",
  "${paths.proc_traj_data_path}/kmco",
  "${paths.proc_traj_data_path}/kmia",
  "${paths.proc_traj_data_path}/panc",
  # cluster_0 unseen-hard
  "${paths.proc_traj_data_path}/kclt",
  "${paths.proc_traj_data_path}/kdca",
  "${paths.proc_traj_data_path}/kden",
  "${paths.proc_traj_data_path}/kiad",
  "${paths.proc_traj_data_path}/kjfk",
  "${paths.proc_traj_data_path}/klax",
  "${paths.proc_traj_data_path}/kmem",
  "${paths.proc_traj_data_path}/kord",
  "${paths.proc_traj_data_path}/kphl",
  "${paths.proc_traj_data_path}/kpit",
  "${paths.proc_traj_data_path}/ksfo",
  "${paths.proc_traj_data_path}/kslc",
  "${paths.proc_traj_data_path}/kstl",
  "${paths.proc_traj_data_path}/phnl",
  # cluster_1 unseen-easy
  "${paths.proc_traj_data_path}/kpvd",
  "${paths.proc_traj_data_path}/ksna",
  # cluster_1 unseen-hard
  "${paths.proc_traj_data_path}/ksdf",
  # cluster_2 unseen-easy
  "${paths.proc_traj_data_path}/kbdl",
  "${paths.proc_traj_data_path}/kbwi",
  "${paths.proc_traj_data_path}/kfll",
  "${paths.proc_traj_data_path}/kmdw",
  # cluster_2 unseen-hard
  "${paths.proc_traj_data_path}/kbos",
  "${paths.proc_traj_data_path}/kewr",
  "${paths.proc_traj_data_path}/klga",
  "${paths.proc_traj_data_path}/kmci",
  "${paths.proc_traj_data_path}/kmsp",
  "${paths.proc_traj_data_path}/ksea",
]
test_split_path: [
  # cluster_0 unseen-easy
  "${paths.splits_path}/kdfw/kdfw_day_splits.json",
  "${paths.splits_path}/klas/klas_day_splits.json",
  "${paths.splits_path}/kmco/kmco_day_splits.json",
  "${paths.splits_path}/kmia/kmia_day_splits.json",
  "${paths.splits_path}/panc/panc_day_splits.json",
  # cluster_0 unseen-hard
  "${paths.splits_path}/kclt/kclt_day_splits.json",
  "${paths.splits_path}/kdca/kdca_day_splits.json",
  "${paths.splits_path}/kden/kden_day_splits.json",
  "${paths.splits_path}/kiad/kiad_day_splits.json",
  "${paths.splits_path}/kjfk/kjfk_day_splits.json",
  "${paths.splits_path}/klax/klax_day_splits.json",
  "${paths.splits_path}/kmem/kmem_day_splits.json",
  "${paths.splits_path}/kord/kord_day_splits.json",
  "${paths.splits_path}/kphl/kphl_day_splits.json",
  "${paths.splits_path}/kpit/kpit_day_splits.json",
  "${paths.splits_path}/ksfo/ksfo_day_splits.json",
  "${paths.splits_path}/kslc/kslc_day_splits.json",
  "${paths.splits_path}/kstl/kstl_day_splits.json",
  "${paths.splits_path}/phnl/phnl_day_splits.json",
  # cluster_1 unseen-easy
  "${paths.splits_path}/kpvd/kpvd_day_splits.json",
  "${paths.splits_path}/ksna/ksna_day_splits.json",
  # cluster_1 unseen-hard
  "${paths.splits_path}/ksdf/ksdf_day_splits.json",
  # cluster_2 unseen-easy
  "${paths.splits_path}/kbdl/kbdl_day_splits.json",
  "${paths.splits_path}/kbwi/kbwi_day_splits.json",
  "${paths.splits_path}/kfll/kfll_day_splits.json",
  "${paths.splits_path}/kmdw/kmdw_day_splits.json",
  # cluster_2 unseen-hard
  "${paths.splits_path}/kbos/kbos_day_splits.json",
  "${paths.splits_path}/kewr/kewr_day_splits.json",
  "${paths.splits_path}/klga/klga_day_splits.json",
  "${paths.splits_path}/kmci/kmci_day_splits.json",
  "${paths.splits_path}/kmsp/kmsp_day_splits.json",
  "${paths.splits_path}/ksea/ksea_day_splits.json",
]
test_data_tag: [
  # cluster_0 unseen-easy
  "cluster-0-kdfw-unseen-easy",
  "cluster-0-klas-unseen-easy",
  "cluster-0-kmco-unseen-easy",
  "cluster-0-kmia-unseen-easy",
  "cluster-0-panc-unseen-easy",
  # cluster_0 unseen-hard
  "cluster-0-kclt-unseen-hard",
  "cluster-0-kdca-unseen-hard",
  "cluster-0-kden-unseen-hard",
  "cluster-0-kiad-unseen-hard",
  "cluster-0-kjfk-unseen-hard",
  "cluster-0-klax-unseen-hard",
  "cluster-0-kmem-unseen-hard",
  "cluster-0-kord-unseen-hard",
  "cluster-0-kphl-unseen-hard",
  "cluster-0-kpit-unseen-hard",
  "cluster-0-ksfo-unseen-hard",
  "cluster-0-kslc-unseen-hard",
  "cluster-0-kstl-unseen-hard",
  "cluster-0-phnl-unseen-hard",
  # cluster_1 unseen-easy
  "cluster-1-kpvd-unseen-easy",
  "cluster-1-ksna-unseen-easy",
  # cluster_1 unseen-hard
  "cluster-1-ksdf-unseen-hard",
  # cluster_2 unseen-easy
  "cluster-2-kbdl-unseen-easy",
  "cluster-2-kbwi-unseen-easy",
  "cluster-2-kfll-unseen-easy",
  "cluster-2-kmdw-unseen-easy",
  # cluster_2 unseen-hard
  "cluster-2-kbos-unseen-hard",
  "cluster-2-kewr-unseen-hard",
  "cluster-2-klga-unseen-hard",
  "cluster-2-kmci-unseen-hard",
  "cluster-2-kmsp-unseen-hard",
  "cluster-2-ksea-unseen-hard",
]
