defaults:
  - default.yaml

tag: 'amelia'

base_path: ./data/
graph_data_version: a42v01
traj_data_version: a42v01

train_data_path: [
  "${paths.proc_traj_data_path}/kmsy"
] # list of paths to the training data
train_split_path: [
  "${paths.splits_path}/kmsy/kmsy_day_splits.json"
] # list of data spliting files for training data
train_data_tag: [
  "kmsy-training"
]

val_data_path: [
  "${paths.proc_traj_data_path}/kmsy"
]
val_split_path: [
  "${paths.splits_path}/kmsy/kmsy_day_splits.json"
] # list of data spliting files for validation data
val_data_tag: [
  "kmsy-validation"
]

test_data_path: [
  "${paths.proc_traj_data_path}/kmsy"
]
test_split_path: [
  "${paths.splits_path}/kmsy/kmsy_day_splits.json"
] # list of data spliting files for test data
test_data_tag: [
  "kmsy-test"
]
