_target_: scenchar.features.individual_features.IndividualFeatures
config:
  return_criteria: ${return_criteria} # Can be 'critical', 'average', or 'none'

  features:
    - speed
    - acceleration
    - deceleration
    - jerk
    - waiting_period
    - waiting_intervals
    - waiting_distances
