defaults:
 - interaction_features.yaml

_target_: scorer.interaction_scorer.InteractionScorer

config:
  weights:
    speed: 0.1
    acceleration: 1.0
    deceleration: 1.0
    jerk: 1.0
    waiting_period: 1.0
    waiting_intervals: 1.0
    waiting_distances: 1.0

  detections:
    speed: 10
    acceleration: 10
    deceleration: 10
    jerk: 10
    waiting_period: 8
    waiting_intervals: 8
    waiting_distances: 8
