_target_: features.interaction_features.InteractionFeatures
config:
  return_criteria: ${return_criteria} # Can be 'critical', 'average', or 'none'
  
  features:
    - separation
    - intersection
    - mttcp