defaults:
  - _self_
  - paths: waymo
  - dataset: waymo
  - viz: waymo
  - processor: features
  - characterizer: feature  

seed: 42
num_scenarios: null
num_shards: 10
shard_index: 0
step: 5

parallel: false
batch_size: 1
num_workers: 0
shuffle: false
save: true

scenario_type: 'gt'
return_criteria: 'critical'