defaults:
  - _self_
  - paths: base_paths
  - dataset: waymo
  - processor: features
  - characterizer: feature  

seed: 42
num_scenarios: null
num_shards: 10
shard_index: 0

parallel: true
batch_size: 4
num_workers: 4
shuffle: false
save: true

scenario_type: 'gt'
