defaults:
  - _self_
  - paths: base_paths
  - dataset: waymo
  - processor: features
  - feature: feature  

seed: 42
num_scenarios: null
num_processes: 10
num_shards: 10
shard_index: 0
save: true

parallel: true
scenario_type: 'gt'