defaults:
  - default.yaml

# This configuration contains the airports for which we have critical scenarios for the purposes of training trajectory
# prediction models on the same environemnts.
airport: [
  # keep-sorted start
  "katl",
  "kbos",
  "kdca",
  "kdfw",
  "kewr",
  "khou",
  "kjfk",
  "klas",
  "klax",
  "klga",
  "kmco",
  "kmdw",
  "kmem",
  "kmia",
  "kmsy",
  "kord",
  "ksan",
  "ksea",
  "ksfo",
  "kslc",
  "panc",
  # keep-sorted end
] # ICAO code or use keyword all for all airports
