defaults:
  - default.yaml
  - wayformer.yaml # Model's backbone architecture directly builds from Wayformer

_target_: safeair.models.scenetokens.SceneTokens
model_name: scenetokens
extra_tags: ${model.base_tags}_${model.tokenizer_tags}_${model.motion_decoder_tags}_${model.criterion_tags}

num_classes: 100

# Scenario Classifier Configuration
use_reconstructed: false
token_conditioning: false
tokenizer_name: quantized
tokenizer_tags: num-tokens-${model.tokenizer.num_tokens}_normalize-${model.tokenizer.normalize}
tokenizer:
  _target_: safeair.models.scene.tokenizers.quantized_tokenizer.QuantizedTokenizer
  num_queries: ${model.num_modes}
  hidden_size: 256
  num_tokens: ${model.num_classes}
  reduction_factor: 2
  normalize: true

motion_decoder_tags: num-tokens-${model.tokenizer.num_tokens}_reconstructed-conditioning-${model.use_reconstructed}_token-conditioning-${model.token_conditioning}
motion_decoder:
  _target_: safeair.models.scene.decoder.TrajectoryDecoder
  num_modes: ${model.num_modes}
  decoding_length: ${scenario.future_len.1}
  hidden_size: 256
  num_tokens: ${model.num_classes}
  token_conditioning: ${model.token_conditioning}

# Model's optimization criterion
criterion_tags: reconstruction-${model.criterion.reconstruction_weight}_trajpred-${model.criterion.trajpred_weight}_tokenization-${model.criterion.tokenization_weight}
criterion:
  _target_: safeair.models.criterion.scenetokens.SceneTokens
  reduction: 'mean'
  reconstruction_weight: 1.0
  trajpred_weight: 1.0
  tokenization_weight: 1.0
