_target_: processors.feature_processor.FeatureProcessor
config:
  scenario_type: ${scenario_type}
  parallel: ${parallel}
  batch_size: 4
  num_processes: ${num_processes}
  save: ${save}
  output_path: ${paths.output_paths.feature_cache_path}