_target_: processors.scores_processor.ScoresProcessor
config:
  scenario_type: ${scenario_type}
  parallel: ${parallel}
  batch_size: 4
  num_processes: ${num_processes}
  save: ${save}

  feature_paths:
    base_features: ${paths.output_paths.feature_cache_path}/base_feature.npz

  output_path: ${paths.output_paths.scores_cache_path}