_target_: utils.datasets.waymo.WaymoData
config:
  seed: ${seed}
  step: 5
  scenario_type: ${scenario_type}  
  scenario_base_path: ${paths.base_path}/new_processed_scenarios_testing
  scenario_meta_path: ${paths.base_path}/new_processed_scenarios_test_infos.pkl

  num_scenarios: ${num_scenarios}
  num_processes: ${num_processes}
  num_shards: ${num_shards}
  shard_index: ${shard_index}
